# Build.Yml
name: Do Nothing Workflow

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "Doing nothing."